### ISSUE TITLE
DLL load failed while importing pycork

### ISSUE THREAD

**Issue by f-p-k** [drlukeparry/pycork#1]
Hello and good evening,

this library sounds like the exact thing I was looking for!
Unfortunately I am having trouble importing it. I can install it using the pip command without any problems, but importing always gives the error below. Sounds like there's some .dll missing or I need to add some Path, but I'm not really sure what to do.
The german part says 'the specified module hasn't been found.'

I'm using python 3.9 under Windows 10. 
I've also tried installing it via Git Bash, but I'm running into a whole lot of CMake related problems there, so I feel like getting it to work this way will be even harder, as I don't know a lot about compiling.

![pycork_err](https://user-images.githubusercontent.com/83970370/150851091-86afc644-fd95-47e6-8680-2c2c31f06228.JPG)

I'd highly appreciate any help!

Greetings, Fabian

**Comment by drlukeparry** [comment]
Hi Fabian,

Thank you for taking the time to report the issue.

I hopefully have fixed the issue. By accident, the wrong option was compiled into the Python library in CMake, so upon running the library, it was trying to locate an external .dll (mpir.dll). This should be now statically compiled into the library and work correctly.

Can you confirm if it is working on version 0.1.1?

Kind Wishes,
Luke

**Comment by f-p-k** [comment]
Hello Luke,

thanks for the quick help! I can indeed import the updated version without any problems.

Best regards,
Fabian
