### ISSUE TITLE
Support for Boolean Union on More Than Two Parts.

### ISSUE THREAD

**Issue by Vipul-M-Rawal** [drlukeparry/pycork#12]
Hi Luke ,

I wanted to know if the Pycork library supports boolean union operations on more than two parts in a single function call. If this feature does not exist, I would like to request its addition.

Use Case:
In projects requiring combining multiple 3D parts, iteratively applying union operations is inefficient and cumbersome. A built-in function to handle various parts would streamline the process and improve performance.

Proposed Solution:
Implement a function such as computeUnionMultiple that accepts a list of meshes and performs the union operation in a single call.

`import numpy as np
import trimesh
import pycork

def boolean_union_multiple(meshes):
    combined_verts, combined_tris = pycork.computeUnionMultiple([mesh.vertices for mesh in meshes], [mesh.faces for mesh in meshes])
    return combined_verts, combined_tris

# Example usage
meshA = trimesh.load_mesh('meshA.off')
meshB = trimesh.load_mesh('meshB.off')
meshC = trimesh.load_mesh('meshC.off')

meshes = [meshA, meshB, meshC]
result_verts, result_tris = boolean_union_multiple(meshes)`

Thank you for considering this request.

**Comment by drlukeparry** [comment]
It is simpler to recreate your own python function for this, which is also done via Trimesh for concatenation aswell.

This library serves to be simply serve as Python bindings for the cork library only.
