### ISSUE TITLE
QuickCSG .exe files

### ISSUE THREAD

**Issue by jqdsn** [drlukeparry/pycork#5]
Hi Dr Luke Parry
  Now I can't access the websit of  http://morpheo.inrialpes.fr/static/QuickCSG/,I would like to know if you can provide the QuickCSG .exe files?
  Sincerely,
  Xiao

**Comment by drlukeparry** [comment]
QuickCSG is not used in this project, nor was it released as an open source package, so unfortunately, I cannot assist on this matter.
