### ISSUE TITLE
Issue in creating binaries using cmake

### ISSUE THREAD

**Issue by Vipul-M-Rawal** [drlukeparry/pycork#8]
I am trying to create binaries using cmake. But I am not able to create binaries using cmake. Can you provide binaries of Pycork? I want to use Pycork in the C++ project.

**Comment by drlukeparry** [comment]
I cannot provide binaries because target platforms. The aim of this project is simply to have a python bindings that are not available Universally.

The cork library compiles straightforwardly on Windows/Linux generally, and you should not have much trouble integrating this into your project.
